package co.fcv.citas.auth;
import io.jsonwebtoken.Claims; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.time.*; import java.security.*; import java.nio.charset.StandardCharsets; import java.util.*;
@Service public class AuthService {
 private final UserRepository users; private final RefreshTokenRepository refreshes; private final PasswordEncoder encoder; private final JwtService jwt; private final JdbcTemplate jdbc; private final long refreshDays; private final boolean exposeRecoveryToken; private final Clock clock;
 public AuthService(UserRepository u,RefreshTokenRepository r,PasswordEncoder e,JwtService j,JdbcTemplate jdbc,@Value("${app.jwt.refresh-days}") long d,@Value("${app.password-recovery.expose-token:false}") boolean expose,Clock clock){users=u;refreshes=r;encoder=e;jwt=j;this.jdbc=jdbc;refreshDays=d;exposeRecoveryToken=expose;this.clock=clock;}
 @Transactional public AuthDtos.TokenResponse register(AuthDtos.RegisterRequest r){if(users.existsByEmailIgnoreCase(r.email())||users.existsByDocumentNumber(r.documentNumber())) throw new ResponseStatusException(HttpStatus.CONFLICT,"Email o documento ya registrado"); if(r.insurancePlanId()!=null){Integer count=jdbc.queryForObject("select count(*) from eps_plans p join eps e on e.id=p.eps_id where p.id=? and p.active=true and e.active=true",Integer.class,r.insurancePlanId());if(count==null||count==0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"El plan seleccionado no está disponible");} UserEntity u=new UserEntity(r.firstName(),r.lastName(),r.documentType(),r.documentNumber(),r.email().toLowerCase(),r.phone(),encoder.encode(r.password()),Role.USER);u=users.save(u);if(r.insurancePlanId()!=null)jdbc.update("insert into user_insurance_affiliations(user_id,plan_id,membership_number,is_current) values(?,?,?,true)",u.getId(),r.insurancePlanId(),"PENDIENTE-"+u.getId());return issue(u);}
 public AuthDtos.TokenResponse login(AuthDtos.LoginRequest r){UserEntity u=users.findByEmailIgnoreCase(r.email()).orElseThrow(this::invalid); if(!u.isActive()||!encoder.matches(r.password(),u.getPasswordHash())) throw invalid(); return issue(u);}
 public AuthDtos.TokenResponse refresh(String raw){try{Claims c=jwt.parseRefresh(raw); if(!"refresh".equals(c.get("type"))) throw invalid(); RefreshTokenEntity rt=refreshes.findByTokenId(c.getId()).orElseThrow(this::invalid); if(rt.getRevokedAt()!=null||rt.getExpiresAt().isBefore(Instant.now())) throw invalid(); rt.revoke(); refreshes.save(rt); return issue(rt.getUser());}catch(Exception e){throw invalid();}}
 public void logout(String raw){try{Claims c=jwt.parseRefresh(raw); refreshes.findByTokenId(c.getId()).ifPresent(t->{t.revoke();refreshes.save(t);});}catch(Exception ignored){}}
 @Transactional public AuthDtos.PasswordRecoveryResponse passwordRecovery(String email){String raw=UUID.randomUUID().toString()+UUID.randomUUID();String hash=sha256(raw);users.findByEmailIgnoreCase(email).ifPresent(u->{LocalDateTime now=LocalDateTime.now(clock);jdbc.update("update password_reset_tokens set used_at=? where user_id=? and used_at is null",now,u.getId());jdbc.update("insert into password_reset_tokens(user_id,token_hash,expires_at) values(?,?,?)",u.getId(),hash,now.plusMinutes(30));});return new AuthDtos.PasswordRecoveryResponse(true,exposeRecoveryToken?raw:null);}
 @Transactional public void passwordReset(String raw,String password){LocalDateTime now=LocalDateTime.now(clock);var rows=jdbc.queryForList("select id,user_id from password_reset_tokens where token_hash=? and used_at is null and expires_at>?",sha256(raw),now);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Token inválido o vencido");long token=((Number)rows.getFirst().get("id")).longValue();long user=((Number)rows.getFirst().get("user_id")).longValue();jdbc.update("update users set password_hash=? where id=?",encoder.encode(password),user);jdbc.update("update password_reset_tokens set used_at=? where id=?",now,token);}
 private String sha256(String value){try{byte[] digest=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte b:digest)out.append(String.format("%02x",b));return out.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private AuthDtos.TokenResponse issue(UserEntity u){String id=UUID.randomUUID().toString(); String refresh=jwt.refresh(u,id); refreshes.save(new RefreshTokenEntity(u,id,Instant.now().plusSeconds(refreshDays*86400))); return new AuthDtos.TokenResponse(jwt.access(u),refresh,jwt.accessSeconds(),view(u));}
 private AuthDtos.UserView view(UserEntity u){return new AuthDtos.UserView(u.getId(),u.getFirstName()+" "+u.getLastName(),u.getEmail(),Set.copyOf(u.getRoles()));}
 private ResponseStatusException invalid(){return new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas");}
}
