package co.fcv.citas.auth;
import jakarta.servlet.DispatcherType; import org.springframework.context.annotation.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.SecurityFilterChain; import org.springframework.web.cors.*; import java.nio.charset.StandardCharsets; import java.util.*;
@Configuration public class SecurityConfig {
 @Value("${app.cors-origin}") String corsOrigin;
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 // ERROR/FORWARD quedan abiertos: si no, cualquier 400/403/404/409 reenviado a /error llegaba al cliente como 401.
 @Bean SecurityFilterChain filterChain(HttpSecurity h,JwtAuthenticationFilter f)throws Exception{return h.csrf(c->c.disable()).cors(c->c.configurationSource(cors())).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint((req,res,ex)->{res.setStatus(401);res.setContentType("application/json");res.setCharacterEncoding(StandardCharsets.UTF_8.name());res.getWriter().write("{\"status\":401,\"error\":\"Unauthorized\",\"message\":\"Autenticación requerida\",\"fieldErrors\":[],\"path\":\""+req.getRequestURI().replace("\"","")+"\"}");})).authorizeHttpRequests(a->a.dispatcherTypeMatchers(DispatcherType.ERROR,DispatcherType.FORWARD).permitAll().requestMatchers("/error","/api/auth/**","/api/v1/catalogs/**","/api/v1/availability","/actuator/health").permitAll().anyRequest().authenticated()).addFilterBefore(f,org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.class).build();}
 private CorsConfigurationSource cors(){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(List.of(corsOrigin));c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("Authorization","Content-Type"));UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
