-- Adopta el modelo de agendamiento ya existente en entornos persistentes.
-- IF NOT EXISTS permite crear el mismo núcleo en instalaciones nuevas sin tocar datos previos.
CREATE TABLE IF NOT EXISTS locations (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(20) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, address VARCHAR(255) NOT NULL DEFAULT '', city VARCHAR(100), department VARCHAR(100), active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS insurance_regimes (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL);
CREATE TABLE IF NOT EXISTS eps (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS eps_plans (id BIGINT AUTO_INCREMENT PRIMARY KEY, eps_id BIGINT NOT NULL, regime_id BIGINT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(eps_id, code));
CREATE TABLE IF NOT EXISTS user_insurance_affiliations (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, plan_id BIGINT NOT NULL, membership_number VARCHAR(80) NOT NULL, is_current BOOLEAN NOT NULL DEFAULT TRUE, valid_from DATE, valid_to DATE, UNIQUE(user_id, plan_id, membership_number));
CREATE TABLE IF NOT EXISTS specialties (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, appointment_duration_minutes INT NOT NULL DEFAULT 30, is_general BOOLEAN NOT NULL DEFAULT FALSE, requires_admin_approval BOOLEAN NOT NULL DEFAULT TRUE, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS professionals (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL UNIQUE, professional_code VARCHAR(40) NOT NULL UNIQUE, license_number VARCHAR(80) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS professional_specialties (professional_id BIGINT NOT NULL, specialty_id BIGINT NOT NULL, is_primary BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY(professional_id, specialty_id));
CREATE TABLE IF NOT EXISTS professional_locations (professional_id BIGINT NOT NULL, location_id BIGINT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY(professional_id, location_id));
CREATE TABLE IF NOT EXISTS availability_blocks (id BIGINT AUTO_INCREMENT PRIMARY KEY, professional_id BIGINT NOT NULL, location_id BIGINT NOT NULL, available_date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS appointment_statuses (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, is_terminal BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS appointments (id BIGINT AUTO_INCREMENT PRIMARY KEY, patient_user_id BIGINT NOT NULL, professional_id BIGINT NOT NULL, location_id BIGINT NOT NULL, specialty_id BIGINT NOT NULL, insurance_affiliation_id BIGINT, status_id BIGINT NOT NULL, reason VARCHAR(500), scheduled_start_at TIMESTAMP NOT NULL, scheduled_end_at TIMESTAMP NOT NULL, created_by_user_id BIGINT NOT NULL, approved_by_user_id BIGINT, approved_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS professional_slots (id BIGINT AUTO_INCREMENT PRIMARY KEY, availability_block_id BIGINT NOT NULL, start_at TIMESTAMP NOT NULL, end_at TIMESTAMP NOT NULL, appointment_id BIGINT, UNIQUE(availability_block_id, start_at));
CREATE TABLE IF NOT EXISTS appointment_status_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, appointment_id BIGINT NOT NULL, status_id BIGINT NOT NULL, changed_by_user_id BIGINT, change_source VARCHAR(20) NOT NULL DEFAULT 'USER', reason VARCHAR(500), changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reschedule_request_statuses (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL);
CREATE TABLE IF NOT EXISTS reschedule_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY, appointment_id BIGINT NOT NULL, requested_by_user_id BIGINT NOT NULL, requested_location_id BIGINT NOT NULL, status_id BIGINT NOT NULL, previous_start_at TIMESTAMP NOT NULL, previous_end_at TIMESTAMP NOT NULL, requested_start_at TIMESTAMP NOT NULL, requested_end_at TIMESTAMP NOT NULL, decision_reason VARCHAR(500), decided_by_user_id BIGINT, decided_at TIMESTAMP, patient_action_after_rejection VARCHAR(30));
